import type { Staff, Client, Project, PayrollRecord, ProjectPhase, PhaseStatus } from '@/types';

export const mockStaff: Staff[] = [
  {
    id: '1',
    name: 'Karthik Raja',
    email: 'karthik@boxway.in',
    role: 'admin',
    phone: '+91 98765 0101',
    joiningDate: '2020-03-15',
    salary: 95000,
    assignedProjects: ['1', '2'],
  },
  {
    id: '2',
    name: 'Arjun Venkat',
    email: 'arjun@boxway.in',
    role: 'architect',
    phone: '+91 98765 0102',
    joiningDate: '2021-06-01',
    salary: 85000,
    assignedProjects: ['1', '3'],
  },
  {
    id: '3',
    name: 'Priya Mani',
    email: 'priya@boxway.in',
    role: 'hr',
    phone: '+91 98765 0103',
    joiningDate: '2022-01-10',
    salary: 65000,
    assignedProjects: [],
  },
  {
    id: '4',
    name: 'Michael Sundar',
    email: 'michael@boxway.in',
    role: 'accountant',
    phone: '+91 98765 0104',
    joiningDate: '2021-09-20',
    salary: 70000,
    assignedProjects: [],
  },
  {
    id: '5',
    name: 'Alex Pandian',
    email: 'alex@boxway.in',
    role: 'intern',
    phone: '+91 98765 0105',
    joiningDate: '2024-01-15',
    salary: 35000,
    assignedProjects: ['2'],
  },
  {
    id: '6',
    name: 'Laxmi Narayan',
    email: 'laxmi@boxway.in',
    role: 'architect',
    phone: '+91 98765 0106',
    joiningDate: '2022-04-01',
    salary: 80000,
    assignedProjects: ['2', '4'],
  },
  {
    id: '7',
    name: 'David Prabhu',
    email: 'david@boxway.in',
    role: 'architect',
    phone: '+91 98765 0107',
    joiningDate: '2023-02-15',
    salary: 75000,
    assignedProjects: ['3', '4'],
  },
];

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'KJS Infrastructure Pvt Ltd',
    email: 'contact@kjsinfra.in',
    phone: '+91 98765 1001',
    company: 'KJS Infrastructure Pvt Ltd',
    siteLocation: 'Plot No. 89, Marine Drive, Kochi, Kerala',
    contractValue: 2500000,
    contractDate: '2024-01-15',
    projects: ['1'],
    paymentStatus: 'partial',
    totalPaid: 1500000,
  },
  {
    id: '2',
    name: 'Cauvery Residences LLC',
    email: 'info@cauveryres.in',
    phone: '+91 98765 1002',
    company: 'Cauvery Residences LLC',
    siteLocation: '456 River Road, Richmond Town, Bengaluru, Karnataka',
    contractValue: 1800000,
    contractDate: '2024-02-20',
    projects: ['2'],
    paymentStatus: 'pending',
    totalPaid: 360000,
  },
  {
    id: '3',
    name: 'Deccan Estates',
    email: 'projects@deccanestates.in',
    phone: '+91 98765 1003',
    company: 'Deccan Estates',
    siteLocation: '789 Valley View, Banjara Hills, Hyderabad, Telangana',
    contractValue: 3200000,
    contractDate: '2024-03-10',
    projects: ['3'],
    paymentStatus: 'partial',
    totalPaid: 2000000,
  },
  {
    id: '4',
    name: 'Nilgiri Commercial Group',
    email: 'dev@nilgiricg.in',
    phone: '+91 98765 1004',
    company: 'Nilgiri Commercial Group',
    siteLocation: '321 Summit Ave, Race Course Road, Coimbatore, Tamil Nadu',
    contractValue: 4500000,
    contractDate: '2024-04-05',
    projects: ['4'],
    paymentStatus: 'pending',
    totalPaid: 900000,
  },
  {
    id: '5',
    name: 'Marina Properties',
    email: 'info@marinaproperties.in',
    phone: '+91 98765 1005',
    company: 'Marina Properties',
    siteLocation: '555 Harbor Lane, ECR, Chennai, Tamil Nadu',
    contractValue: 2100000,
    contractDate: '2024-05-12',
    projects: [],
    paymentStatus: 'completed',
    totalPaid: 2100000,
  },
];

const createPhases = (statuses: PhaseStatus[]): Project['phases'] => {
  const phases: ProjectPhase[] = [
    'concept-design',
    '3d-visualization',
    'approval-drawings',
    'working-drawings',
    'site-execution',
    'completion',
  ];

  return phases.map((phase, index) => ({
    phase,
    status: statuses[index] || 'pending',
  }));
};

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Deccan Tower Complex',
    description: 'A 45-story mixed-use development featuring retail, office, and residential spaces with sustainable design principles.',
    clientId: '1',
    assignedStaff: ['1', '2'],
    status: 'active',
    phases: createPhases(['completed', 'completed', 'in-progress', 'pending', 'pending', 'pending']),
    startDate: '2024-02-01',
    deadline: '2025-12-31',
    budget: 2500000,
    progress: 35,
  },
  {
    id: '2',
    name: 'Cauvery Vista Apartments',
    description: 'Premium waterfront residential complex with 120 units featuring panoramic river views.',
    clientId: '2',
    assignedStaff: ['5', '6'],
    status: 'active',
    phases: createPhases(['completed', 'in-progress', 'pending', 'pending', 'pending', 'pending']),
    startDate: '2024-03-15',
    deadline: '2025-09-30',
    budget: 1800000,
    progress: 22,
  },
  {
    id: '3',
    name: 'Annamalai Community Center',
    description: 'Eco-friendly community center with recreational facilities, meeting spaces, and tribal heritage gardens.',
    clientId: '3',
    assignedStaff: ['2', '7'],
    status: 'active',
    phases: createPhases(['completed', 'completed', 'completed', 'in-progress', 'pending', 'pending']),
    startDate: '2024-01-10',
    deadline: '2025-06-30',
    budget: 3200000,
    progress: 58,
  },
  {
    id: '4',
    name: 'Nilgiri Tech Park',
    description: 'Modern IT campus with innovative workspace design and integrated sustainable amenities.',
    clientId: '4',
    assignedStaff: ['6', '7'],
    status: 'planning',
    phases: createPhases(['in-progress', 'pending', 'pending', 'pending', 'pending', 'pending']),
    startDate: '2024-06-01',
    deadline: '2026-03-31',
    budget: 4500000,
    progress: 8,
  },
];

export const mockPayroll: PayrollRecord[] = [
  { id: '1', staffId: '1', month: 'January', year: 2025, baseSalary: 95000 / 12, attendance: 22, totalDays: 22, deductions: 200, bonus: 500, netSalary: 8216.67, status: 'paid' },
  { id: '2', staffId: '2', month: 'January', year: 2025, baseSalary: 85000 / 12, attendance: 21, totalDays: 22, deductions: 150, bonus: 0, netSalary: 6930.30, status: 'paid' },
  { id: '3', staffId: '3', month: 'January', year: 2025, baseSalary: 65000 / 12, attendance: 22, totalDays: 22, deductions: 100, bonus: 0, netSalary: 5316.67, status: 'paid' },
  { id: '4', staffId: '4', month: 'January', year: 2025, baseSalary: 70000 / 12, attendance: 20, totalDays: 22, deductions: 180, bonus: 200, netSalary: 5321.21, status: 'approved' },
  { id: '5', staffId: '5', month: 'January', year: 2025, baseSalary: 35000 / 12, attendance: 22, totalDays: 22, deductions: 50, bonus: 0, netSalary: 2866.67, status: 'pending' },
  { id: '6', staffId: '6', month: 'January', year: 2025, baseSalary: 80000 / 12, attendance: 22, totalDays: 22, deductions: 120, bonus: 300, netSalary: 6846.67, status: 'approved' },
  { id: '7', staffId: '7', month: 'January', year: 2025, baseSalary: 75000 / 12, attendance: 19, totalDays: 22, deductions: 250, bonus: 0, netSalary: 5147.73, status: 'pending' },
];

export const projectPhaseLabels: Record<string, string> = {
  'concept-design': 'Concept Design',
  '3d-visualization': '3D Visualization',
  'approval-drawings': 'Approval Drawings',
  'working-drawings': 'Working Drawings',
  'site-execution': 'Site Execution',
  'completion': 'Completion',
};

export const roleLabels: Record<string, string> = {
  admin: 'Administrator',
  architect: 'Architect',
  hr: 'HR Manager',
  accountant: 'Accountant',
  intern: 'Intern',
};

